# Generated by Django 5.0.6 on 2024-06-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0018_image_image_url_alter_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user_keyword",
        ),
        migrations.AddField(
            model_name="customer",
            name="code",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Код для регистрации"
            ),
        ),
    ]
