# Generated by Django 5.0.6 on 2025-08-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0025_alter_order_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="GaugeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
