# Generated by Django 5.0.6 on 2025-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0026_gaugevalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, default=" ", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_link",
            field=models.CharField(blank=True, default=" ", max_length=500, null=True),
        ),
    ]
