# Generated by Django 5.0.6 on 2025-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_alter_order_payment_id_alter_order_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
