# Generated by Django 5.0.6 on 2025-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0028_customer_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
