# Generated by Django 5.0.6 on 2025-08-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_order_create_at'),
        ('src', '0030_auto_20250813_1454'),
    ]

    operations = [
    ]
