# Generated by Django 5.0.6 on 2025-09-25 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0032_booking_create_at_image_create_at_master_create_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GaugeValue",
        ),
    ]
