# Generated by Django 4.2.6 on 2024-05-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=0, max_length=30, verbose_name='Номер телефона клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='length_time',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Длительность процедуры'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('in-progress', 'В прогрессе'), ('done', 'Закончено')], default='new', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
