# Generated by Django 4.2.6 on 2024-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_master_is_verified_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='src.service'),
        ),
    ]
