# Generated by Django 5.0.6 on 2024-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_rename_addidional_info_customer_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_notice",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Коментарий"
            ),
        ),
    ]
