# Generated by Django 4.2.6 on 2024-05-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_order_services_order_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master',
        ),
    ]
