# Generated by Django 4.2.6 on 2024-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_booking_booking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_end_time',
            field=models.TimeField(blank=True, editable=False, null=True, verbose_name='Длительность процедуры'),
        ),
    ]
