# Generated by Django 5.0.6 on 2024-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_master_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='code',
            field=models.IntegerField(default=17417, verbose_name='Слово пароль'),
        ),
    ]
