# Generated by Django 5.0.6 on 2024-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_master_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='main_image_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
