# Generated by Django 5.0.6 on 2024-06-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_customer_name_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя'),
        ),
    ]
