# Generated by Django 5.0.6 on 2024-09-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_alter_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='src.service'),
        ),
    ]
