import os


from dotenv import load_dotenv

load_dotenv("notigy.env")

RABBIT_MQ_CONNECTION_URL = os.getenv("RABBIT_MQ_CONNECTION_URL")
RABBIT_MQ_CHANNEL_NAME = os.getenv("RABBIT_MQ_CHANNEL_NAME")

CLIENT_BOT_TOKEN = os.getenv("CLIENT_BOT_TOKEN")
MASTER_BOT_TOKEN = os.getenv("MASTER_BOT_TOKEN")
ORGANIZATION_BOT_TOKEN = os.getenv("ORGANIZATION_BOT_TOKEN")
MODERATOR_BOT_TOKEN = os.getenv("MODERATOR_BOT_TOKEN")

MONGO_DB_CONNECTION_URL = os.getenv("MONGO_DB_CONNECTION_URL")
